"use client";
import { useEffect } from "react";

import { Geist, Geist_Mono } from "next/font/google";
import axiosInstance from "@/utils/axios";
import "./globals.css";
import useAuthStore from "@/Store/useAuthStore.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const setAuth = useAuthStore((state) => state.setAuth);

  useEffect(() => {
    const checkAuth = async () => {
      try {
        const response = await axiosInstance.get("/me");
        console.log(response.data);
        setAuth(true, response.data);
      } catch (error) {
        if (error.response && error.response.status === 401) {
          setAuth(false, null);
        } else {
          console.log(error.response);
        }
      }
    };

    checkAuth();
  }, [setAuth]);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
